const express = require('express');
const router = express.Router();
const VolumeTransactionController = require('../controllers/volumeTransactionController');
const { handleHttpError, divideByDecimals, parseCurrencyString } = require('../utils'); // Asumiendo que tienes un manejador de errores
const { response } = require('../db'); // Asumiendo que tienes una función de respuesta
const auth = require('../middleware/auth');
const authAdmin = require('../middleware/authAdmin');
const axios = require("axios");
const volumeTransactionModel = require('../models/volumeTransactionModel');
const logger = require('node-color-log');

async function getTransactionWallet(walletAddress = process.env.WALLET_TRON_DEPOSIT) {
    try {
        const url = `https://api.trongrid.io/v1/accounts/${walletAddress}/transactions/trc20`;


        const response = await axios.get(url, {
            headers: {
                'TRON-PRO-API-KEY': process.env.TRON_API_KEY
            },
            params: {
                limit: 200,
                only_to: true
            }
        });

        const transactions = response.data.data.filter(tx => tx.to === walletAddress);
        for (let i = 0; i < transactions.length; i++) {
            const t = transactions[i];
            let transaction = {
                methodPay: "Transaction",
                date: new Date(t.block_timestamp),
                receivedAmount: divideByDecimals(t.value, t.token_info.decimals),
                symbol: t.token_info.symbol,
                tx: t.transaction_id,
                walletSend: t.from,
            }
            if (transaction.receivedAmount > 1)
                await volumeTransactionModel.updateOne({ tx: t.transaction_id }, { $set: transaction }, { upsert: true });
        }
        console.log("Transactions inserted in volume", transactions.length);
        // return transactions;
    } catch (error) {
        console.error('Error fetching transactions:', error.message);
        throw error;
    }
    await loadTransactionsExcel()
    setInterval(getTransactionWallet, 10 * 60 * 60 * 1000);//cada 10 hs
}

getTransactionWallet();


async function loadTransactionsExcel() {

    logger.info("insert data excel to volumeTransactions")
    let json = `[
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "11/09/2023",
        "Received Amount (EUR)": "€34,706.08",
        "Received Amount (USD)": "$37,724.00",
        "Total Received": "$37,724.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$37,346.76",
        "Gas Fees": "$8.28",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "$338,872.26",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "11/20/2023",
        "Received Amount (EUR)": "€357.88",
        "Received Amount (USD)": "$389.00",
        "Total Received": "$38,113.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$385.11",
        "Gas Fees": "$2.81",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "12/11/2023",
        "Received Amount (EUR)": "€4,600.00",
        "Received Amount (USD)": "$5,000.00",
        "Total Received": "$43,113.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$4,950.00",
        "Gas Fees": "$0",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/e26edadeafb8d19ad8d22bf7b6bc6bb7f23e7f7bff3b4ac361caae4d2cb57745",
        "Wallet Address": "TYGoPRAZW3TDpYyWNnU3E6DKpvgeBqVhXC",
        "Risk Score": "0.8",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "12/15/2023",
        "Received Amount (EUR)": "€4,600.00",
        "Received Amount (USD)": "$5,000.00",
        "Total Received": "$48,113.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$4,950.00",
        "Gas Fees": "$0",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/39468af40fa50739ce4fff546b65246299d489b6f0fece9863898b7b1b2ef488",
        "Wallet Address": "TYGoPRAZW3TDpYyWNnU3E6DKpvgeBqVhXC",
        "Risk Score": "0.8",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "12/20/2023",
        "Received Amount (EUR)": "€15,180.00",
        "Received Amount (USD)": "$16,500.00",
        "Total Received": "$64,613.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$16,335.00",
        "Gas Fees": "$0",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/da79c2c228217a72908c3043c9423a5b64946b81a8ee9803219d1eb00ca32b74",
        "Wallet Address": "TYGoPRAZW3TDpYyWNnU3E6DKpvgeBqVhXC",
        "Risk Score": "0.8",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "1/6/2024",
        "Received Amount (EUR)": "€4,600.00",
        "Received Amount (USD)": "$5,000.00",
        "Total Received": "$69,613.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$4,950.00",
        "Gas Fees": "$0",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/2edd17c86974e38ba61f19dd13eaa9f1df4b63a2633736c0a293ba948ab0b44c",
        "Wallet Address": "TYGoPRAZW3TDpYyWNnU3E6DKpvgeBqVhXC",
        "Risk Score": "0.8",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "1/10/2024",
        "Received Amount (EUR)": "€11,040.00",
        "Received Amount (USD)": "$12,000.00",
        "Total Received": "$81,613.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$11,880.00",
        "Gas Fees": "$2.86",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/cb63f8739d7e120d2f474103eeb107ab5bc8694b90221718ffbfb074b68e369d",
        "Wallet Address": "TVPjfJzRrkvoNgtV8Xvob8ZApEaEWbXC2h",
        "Risk Score": "0.1",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "1/18/2024",
        "Received Amount (EUR)": "€4,600.00",
        "Received Amount (USD)": "$5,000.00",
        "Total Received": "$86,613.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$4,950.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/b5f4d2d00eccf1b2fe157afb69531baa021d05e7e9b04a5c94e7906e91ab6cf3",
        "Wallet Address": "TYGoPRAZW3TDpYyWNnU3E6DKpvgeBqVhXC",
        "Risk Score": "0.8",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "1/18/2024",
        "Received Amount (EUR)": "€59,800.00",
        "Received Amount (USD)": "$65,000.00",
        "Total Received": "$151,613.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$64,350.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/34e9ac65a00ab889d30fc19415f02258d5ccd88ca7e9af615e41f9fb0f61c895",
        "Wallet Address": "TLSNHNjVAJM4eDVS2CtJtBEysPmuKDdtyW",
        "Risk Score": "0.1",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "Incurred $80 additional fee because USDT conversion rate is down",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "1/24/2024",
        "Received Amount (EUR)": "€6,421.60",
        "Received Amount (USD)": "$6,980.00",
        "Total Received": "$158,593.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$6,910.20",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TYTdFF1RuEvB5SwGdTZoawY4NMMchMExYB",
        "Risk Score": "0.1",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "1/24/2024",
        "Received Amount (EUR)": "€14,536.00",
        "Received Amount (USD)": "$15,800.00",
        "Total Received": "$174,393.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$15,642.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TXb3ShK1k9tSHBBiVyYz8yBzKo3jBpAt5q",
        "Risk Score": "0.2",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "1/24/2024",
        "Received Amount (EUR)": "€7,360.00",
        "Received Amount (USD)": "$8,000.00",
        "Total Received": "$182,393.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$7,920.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TJL7ikFJwi9UbmgenQovWNPXwk3CZmmohB",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "2/1/2024",
        "Received Amount (EUR)": "€46,460.00",
        "Received Amount (USD)": "$50,500.00",
        "Total Received": "$232,893.00",
        "Shield Fee": "1.0%",
        "Client Transfer": "$49,995.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TQzhQ3SqymgbhrP2sSgyLkSynLgEGqAjRi - Hong Kong Supplier 1",
        "Risk Score": "0.1",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "2/5/2024",
        "Received Amount (EUR)": "€41,652.32",
        "Received Amount (USD)": "$45,274.26",
        "Total Received": "$278,167.26",
        "Shield Fee": "1.0%",
        "Client Transfer": "$44,821.52",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TQzhQ3SqymgbhrP2sSgyLkSynLgEGqAjRi - Hong Kong Supplier 1",
        "Risk Score": "0.1",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "2/5/2024",
        "Received Amount (EUR)": "€21,464.52",
        "Received Amount (USD)": "$23,331.00",
        "Total Received": "$301,498.26",
        "Shield Fee": "1.0%",
        "Client Transfer": "$23,097.69",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TH3FF58t7hExthCmNUn7VThT2vvsvmkN3m - Howell (Hong Kong Supplier)",
        "Risk Score": "0.6",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "2/6/2024",
        "Received Amount (EUR)": "€34,384.08",
        "Received Amount (USD)": "$37,374.00",
        "Total Received": "$338,872.26",
        "Shield Fee": "1.0%",
        "Client Transfer": "$37,000.26",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TQzhQ3SqymgbhrP2sSgyLkSynLgEGqAjRi",
        "Risk Score": "0.1",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Tron",
        "Notes": "This one technically fell through on client end but we were still paid our service fee",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "2/21/2024",
        "Received Amount (EUR)": "€18,399.08",
        "Received Amount (USD)": "$19,999.00",
        "Total Received": "$358,871.26",
        "Shield Fee": "1.0%",
        "Client Transfer": "$19,799.01",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/8a809e86b62638311862b0b2c940669f7cccea3faf94a4491cd7ee5a1d80ae68",
        "Wallet Address": "TJDENsfBJs4RFETt1X1W8wMDc8M5XnJhCe",
        "Risk Score": "N/A",
        "Self-hosted?": "FALSO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Pre-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "2/22/2024",
        "Received Amount (EUR)": "€28,422.48",
        "Received Amount (USD)": "$30,894.00",
        "Total Received": "$389,765.26",
        "Shield Fee": "1.0%",
        "Client Transfer": "$30,585.06",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TK8CNZcRZgpGPJA76z5mM2HorAxSjxpsWS",
        "Risk Score": "0.3",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Kraken",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Post-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "3/25/2024",
        "Received Amount (EUR)": "€6,690.24",
        "Received Amount (USD)": "$7,272.00",
        "Total Received": "$397,037.26",
        "Shield Fee": "1.0%",
        "Client Transfer": "$7,199.28",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/9a4a6fe06ef41ee9759e9b51d2c8a34c4da77c73d188355410568ecb404eb049",
        "Wallet Address": "TTqEDJTe9MgnQtXXsH9EHw9werLkRvSJuW",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Post-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "4/9/2024",
        "Received Amount (EUR)": "€9,200.00",
        "Received Amount (USD)": "$10,000.00",
        "Total Received": "$407,037.26",
        "Shield Fee": "1.0%",
        "Client Transfer": "$9,900.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/2fedc2dacc9e7dfb8474efcc2561e4fff7f655e0aaf6efad5ab7d74096f776aa",
        "Wallet Address": "TQd3dABHxFZRuwZwmeMH4rkKkvmNaG8YYk",
        "Risk Score": "0.1",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Post-Compliance",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "5/6/2024",
        "Received Amount (EUR)": "€9,913.92",
        "Received Amount (USD)": "$10,776.00",
        "Total Received": "$417,813.26",
        "Shield Fee": "1.0%",
        "Client Transfer": "$10,668.24",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/1440f33a96f4acb89273279d578d468991a0ca746a01d0104a82327e5c541b6c",
        "Wallet Address": "TVx7sgBwgMdMBpU8aM5GmhsHSfoKLDTYU2",
        "Risk Score": "0.2",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "5/31/2024",
        "Received Amount (EUR)": "€193.20",
        "Received Amount (USD)": "$210.00",
        "Total Received": "$418,023.26",
        "Shield Fee": "0.0%",
        "Client Transfer": "$210.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x84070244a778D6eBAa14C1797b083853D4D7874A",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "6/10/2024",
        "Received Amount (EUR)": "€358.80",
        "Received Amount (USD)": "$390.00",
        "Total Received": "$418,413.26",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x84070244a778D6eBAa14C1797b083853D4D7874A",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "6/12/2024",
        "Received Amount (EUR)": "€2,966.08",
        "Received Amount (USD)": "$3,224.00",
        "Total Received": "$421,637.26",
        "Shield Fee": "1.0%",
        "Client Transfer": "$3,191.76",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/eaf3f497aacc311e9e501d68d7cdb65b30ded5bf35a04639dad8d19f51862b37",
        "Wallet Address": "TBrAgWDVr9YfjgkpGiXpsxSAfWStwYT15S",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "6/13/2024",
        "Received Amount (EUR)": "€303.60",
        "Received Amount (USD)": "$330.00",
        "Total Received": "$421,967.26",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x953e2684B13B69b782ce6763D3ebaEf39343f5e7",
        "Risk Score": "N/A",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Luis Carchi",
        "Method of Pay": "Wire",
        "Date": "6/14/2024",
        "Received Amount (EUR)": "€15,166.20",
        "Received Amount (USD)": "$16,485.00",
        "Total Received": "$438,452.26",
        "Shield Fee": "1.0%",
        "Client Transfer": "$16,320.15",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://etherscan.io/tx/0xf6fe606450a74e01486e2350e6551c6cd4607f64a3f3b83e85a3c6f5588366c9",
        "Wallet Address": "0xA9D1e08C7793af67e9d92fe308d5697FB81d3E43",
        "Risk Score": "N/A",
        "Self-hosted?": "FALSO",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Ethereum",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Corey McCauley",
        "Method of Pay": "Wire",
        "Date": "6/15/2024",
        "Received Amount (EUR)": "€458.40",
        "Received Amount (USD)": "$498.26",
        "Total Received": "$438,950.52",
        "Shield Fee": "1.0%",
        "Client Transfer": "$493.28",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0xAe2D4617c862309A3d75A0fFB358c7a5009c673F",
        "Risk Score": "N/A",
        "Self-hosted?": "FALSO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "ETH-USD",
        "Blockchain": "Ethereum",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "6/17/2024",
        "Received Amount (EUR)": "€567.64",
        "Received Amount (USD)": "$617.00",
        "Total Received": "$439,567.52",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x84070244a778D6eBAa14C1797b083853D4D7874A",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Gerald Kwazu",
        "Method of Pay": "Wire",
        "Date": "6/18/2024",
        "Received Amount (EUR)": "€23.00",
        "Received Amount (USD)": "$25.00",
        "Total Received": "$439,592.52",
        "Shield Fee": "1.0%",
        "Client Transfer": "$24.75",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "7zMygMkUGoDEp1sDWP5SRdXJMyFjCD7yzeANR8veo6uL",
        "Risk Score": "N/A",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Solana",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "6/20/2024",
        "Received Amount (EUR)": "€269.10",
        "Received Amount (USD)": "$292.50",
        "Total Received": "$440,322.25",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x953e2684B13B69b782ce6763D3ebaEf39343f5e7",
        "Risk Score": "N/A",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "6/20/2024",
        "Received Amount (EUR)": "€395.60",
        "Received Amount (USD)": "$430.00",
        "Total Received": "$440,752.25",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x84070244a778D6eBAa14C1797b083853D4D7874A",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "6/25/2024",
        "Received Amount (EUR)": "€1,416.80",
        "Received Amount (USD)": "$1,540.00",
        "Total Received": "$442,292.25",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x1f9DC6a9AC61FE672797b2C42314722f59FC66A0",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "6/28/2024",
        "Received Amount (EUR)": "€747.04",
        "Received Amount (USD)": "$812.00",
        "Total Received": "$443,104.25",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x953e2684B13B69b782ce6763D3ebaEf39343f5e7",
        "Risk Score": "N/A",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "6/28/2024",
        "Received Amount (EUR)": "€554.76",
        "Received Amount (USD)": "$603.00",
        "Total Received": "$443,707.25",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x84070244a778D6eBAa14C1797b083853D4D7874A",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q2",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "6/29/2024",
        "Received Amount (EUR)": "€8,886.28",
        "Received Amount (USD)": "$9,659.00",
        "Total Received": "$453,366.25",
        "Shield Fee": "1.0%",
        "Client Transfer": "$9,562.41",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/fcc75902ab1e3f9ae6a85427227349e3631e1c5d586da7e5359531b3b6a69094",
        "Wallet Address": "TMWh1ZusNcwdLeSNMxsWQbms6EcgyMkoKn",
        "Risk Score": "0.1",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Edward Calderon",
        "Method of Pay": "PayPal",
        "Date": "7/5/2024",
        "Received Amount (EUR)": "€174.37",
        "Received Amount (USD)": "$189.53",
        "Total Received": "$453,555.78",
        "Shield Fee": "1.0%",
        "Client Transfer": "$187.63",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/a975329e86a89931da0e275f7e09642424e5536c2c19660ef601affbb020d011",
        "Wallet Address": "TQjJspYyu4s27FZ8BQw8Td3HWB3PRD9Bgs",
        "Risk Score": "N/A",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Paypal",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "7/5/2024",
        "Received Amount (EUR)": "€481.16",
        "Received Amount (USD)": "$523.00",
        "Total Received": "$454,078.78",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x84070244a778D6eBAa14C1797b083853D4D7874A",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/5/2024",
        "Received Amount (EUR)": "€9,200.00",
        "Received Amount (USD)": "$10,000.00",
        "Total Received": "$464,078.78",
        "Shield Fee": "0.0%",
        "Client Transfer": "$10,000.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "Free test txn. Didn't inform Rampable so take $80 loss",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Arda Erturk",
        "Method of Pay": "Wire",
        "Date": "7/9/2024",
        "Received Amount (EUR)": "€9,931.85",
        "Received Amount (USD)": "$10,795.49",
        "Total Received": "$474,874.27",
        "Shield Fee": "1.0%",
        "Client Transfer": "$10,687.54",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TW4n9jyNErxsTWxYXAF3Qmcae6Zaqgk6Un",
        "Risk Score": "N/A",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Tron",
        "Notes": "Seems his bank took $20 in fees when he transferred",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Emmanuel Udotong",
        "Method of Pay": "Wire",
        "Date": "7/9/2024",
        "Received Amount (EUR)": "€460.00",
        "Received Amount (USD)": "$500.00",
        "Total Received": "$475,374.27",
        "Shield Fee": "1.0%",
        "Client Transfer": "$495.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0xd1f23D8F7C097471FEcAFce27eE56012c0b648BD",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "ETH-USD",
        "Blockchain": "Ethereum",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/9/2024",
        "Received Amount (EUR)": "€10,672.00",
        "Received Amount (USD)": "$11,600.00",
        "Total Received": "$486,974.27",
        "Shield Fee": "0.0%",
        "Client Transfer": "$11,600.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "Free test txn",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/9/2024",
        "Received Amount (EUR)": "€18,400.00",
        "Received Amount (USD)": "$20,000.00",
        "Total Received": "$506,974.27",
        "Shield Fee": "0.0%",
        "Client Transfer": "$20,000.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "Free test txn",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/10/2024",
        "Received Amount (EUR)": "€27,600.00",
        "Received Amount (USD)": "$30,000.00",
        "Total Received": "$536,974.27",
        "Shield Fee": "0.5%",
        "Client Transfer": "$29,850.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://explorer.solana.com/tx/2PRcQKu9EmVeX7izAb9iBg2sHj5NHjGtga7sE7aQjwYyP5aoJx1khTAg4znzTWFRRoR4odCo9E3yftNpbwngiqg2",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "First charged transaction. Faced $59.60 Kraken conversion fees because Dakota bugs. But they will refund us.",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/11/2024",
        "Received Amount (EUR)": "€9,200.00",
        "Received Amount (USD)": "$10,000.00",
        "Total Received": "$546,974.27",
        "Shield Fee": "0.5%",
        "Client Transfer": "$9,950.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/faa071139a2301ae2c168f2b76d06b7518c51a439e466e18eeb0ed5790b19d26",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "7/12/2024",
        "Received Amount (EUR)": "€11,247.00",
        "Received Amount (USD)": "$12,225.00",
        "Total Received": "$559,199.27",
        "Shield Fee": "1.0%",
        "Client Transfer": "$12,102.75",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/5275d34b23afea43c4932ff1c721fd66d562ab328358ee2664d115ece0d537a1",
        "Wallet Address": "TVkDL9vJ3cwAmu4WRctMe4JKGxHhaBWt3J",
        "Risk Score": "0.2",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/15/2024",
        "Received Amount (EUR)": "€9,200.00",
        "Received Amount (USD)": "$10,000.00",
        "Total Received": "$569,199.27",
        "Shield Fee": "0.5%",
        "Client Transfer": "$9,950.00",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/54ddc8c82176a5f00ab9ac9319c7c2f70a8ae93c44aa92161e1b518e0303cc16",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "7/15/2024",
        "Received Amount (EUR)": "€706.56",
        "Received Amount (USD)": "$768.00",
        "Total Received": "$569,967.27",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x953e2684B13B69b782ce6763D3ebaEf39343f5e7",
        "Risk Score": "N/A",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "7/15/2024",
        "Received Amount (EUR)": "€395.60",
        "Received Amount (USD)": "$430.00",
        "Total Received": "$570,397.27",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x84070244a778D6eBAa14C1797b083853D4D7874A",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/16/2024",
        "Received Amount (EUR)": "€7,360.00",
        "Received Amount (USD)": "$8,000.00",
        "Total Received": "$578,397.27",
        "Shield Fee": "0.5%",
        "Client Transfer": "$7,960.00",
        "Gas Fees": "$6.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/f7d9d97393f3521aa923e7b1c8a8b04a9a6ca162ceb6715298f2f123ff7d5faf",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/17/2024",
        "Received Amount (EUR)": "€66,239.11",
        "Received Amount (USD)": "$71,999.03",
        "Total Received": "$650,396.30",
        "Shield Fee": "0.5%",
        "Client Transfer": "$71,639.03",
        "Gas Fees": "$6.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/baaeb098e4d166f3e48c4621b008f5eec781e0b4911f7b1a5b36765011005c31",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/18/2024",
        "Received Amount (EUR)": "€9,384.06",
        "Received Amount (USD)": "$10,200.07",
        "Total Received": "$660,596.37",
        "Shield Fee": "0.5%",
        "Client Transfer": "$10,149.07",
        "Gas Fees": "$6.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/4e37a0909112570ccb93662bc675016e15313e39fbd0c437f2efad8e3bbec2b7",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "7/19/2024",
        "Received Amount (EUR)": "€276.00",
        "Received Amount (USD)": "$300.00",
        "Total Received": "$660,896.37",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "TBScmV7L6BNZCxuhyquGcswXgqpaehg5vn",
        "Risk Score": "N/A",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "7/19/2024",
        "Received Amount (EUR)": "€207.00",
        "Received Amount (USD)": "$225.00",
        "Total Received": "$661,121.37",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x953e2684B13B69b782ce6763D3ebaEf39343f5e7",
        "Risk Score": "N/A",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Shield / Devs",
        "Method of Pay": "Wire",
        "Date": "7/19/2024",
        "Received Amount (EUR)": "€524.40",
        "Received Amount (USD)": "$570.00",
        "Total Received": "$661,691.37",
        "Shield Fee": "0.0%",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "VERDADERO",
        "Txn Hash": "",
        "Wallet Address": "0x84070244a778D6eBAa14C1797b083853D4D7874A",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Onramp",
        "Currency Pair": "USD-USDT",
        "Blockchain": "Polygon",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Yaniv Azar",
        "Method of Pay": "Wire",
        "Date": "7/22/2024",
        "Received Amount (EUR)": "€4,600.00",
        "Received Amount (USD)": "$5,000.00",
        "Total Received": "$666,691.37",
        "Shield Fee": "1.0%",
        "Client Transfer": "$4,950.00",
        "Gas Fees": "$6.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://etherscan.io/tx/0xd5cbb1328c846513c6d62ab491de08582c4679024b63d26844bdc54725e13f65",
        "Wallet Address": "0x996922c411AD2d4eC98B95fec7FbFcbD09c75686",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Off-ramp",
        "Currency Pair": "USDC-USD",
        "Blockchain": "Ethereum",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/23/2024",
        "Received Amount (EUR)": "€33,119.08",
        "Received Amount (USD)": "$35,999.00",
        "Total Received": "$702,690.37",
        "Shield Fee": "0.5%",
        "Client Transfer": "$35,819.01",
        "Gas Fees": "$2.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/ac859af7600aa3879cabeeb0ff51f597b6713d4a9a2aa19b0ea0d81768fd5d1d",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/23/2024",
        "Received Amount (EUR)": "€26,680.00",
        "Received Amount (USD)": "$29,000.00",
        "Total Received": "$731,690.37",
        "Shield Fee": "0.5%",
        "Client Transfer": "$28,855.00",
        "Gas Fees": "$2.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/56eaeb183d726322d0eee8d76c08dc4a30addeaf098512cdc9e13e87a4509ccc",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Eze Technologies",
        "Method of Pay": "Wire",
        "Date": "7/23/2024",
        "Received Amount (EUR)": "€8,226.64",
        "Received Amount (USD)": "$8,942.00",
        "Total Received": "$740,632.37",
        "Shield Fee": "1.0%",
        "Client Transfer": "$8,852.58",
        "Gas Fees": "$0.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/ffe015d2da465535030e44146247ff368795cc98f7bb84ea2dbc7f1f739840c5",
        "Wallet Address": "TBrAgWDVr9YfjgkpGiXpsxSAfWStwYT15S",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Rampable",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Lucas (MF Ocean 12)",
        "Method of Pay": "Wire",
        "Date": "7/24/2024",
        "Received Amount (EUR)": "€18,400.00",
        "Received Amount (USD)": "$20,000.00",
        "Total Received": "$760,632.37",
        "Shield Fee": "0.5%",
        "Client Transfer": "$19,900.00",
        "Gas Fees": "$8.00",
        "Completed": "VERDADERO",
        "Txn Hash": "https://tronscan.org/#/transaction/f525efbcb7b9ece64b6812a85f5c78f55aca1470fa08b34488e104df72ca3d3b",
        "Wallet Address": "TAucN8UckSKagM2KE5PkVKZ4XBvSWUwive",
        "Risk Score": "0",
        "Self-hosted?": "VERDADERO",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "USDT-USD",
        "Blockchain": "Tron",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "Q3",
        "Client Name": "Mobius LLC",
        "Method of Pay": "Wire",
        "Date": "7/28/2024",
        "Received Amount (EUR)": "€1,883.10",
        "Received Amount (USD)": "$2,046.85",
        "Total Received": "$762,679.22",
        "Shield Fee": "1.0%",
        "Client Transfer": "$2,026.38",
        "Gas Fees": "$8.00",
        "Completed": "FALSO",
        "Txn Hash": "",
        "Wallet Address": "0xd9Ea0EDFae5977f6cAC2b199fE1453A44BD7D2df",
        "Risk Score": "?",
        "Self-hosted?": "?",
        "KYC/AML": "VERDADERO",
        "Partner": "Dakota",
        "Onramp/Offramp": "Offramp",
        "Currency Pair": "ETH-USD",
        "Blockchain": "Ethereum",
        "Notes": "Received Ola payment of ETH to Femi",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "",
        "Method of Pay": "",
        "Date": "",
        "Received Amount (EUR)": "",
        "Received Amount (USD)": "",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "",
        "Method of Pay": "",
        "Date": "",
        "Received Amount (EUR)": "",
        "Received Amount (USD)": "",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "",
        "Method of Pay": "",
        "Date": "June Month (6/10-7/10)",
        "Received Amount (EUR)": "",
        "Received Amount (USD)": "",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "",
        "Method of Pay": "",
        "Date": "",
        "Received Amount (EUR)": "",
        "Received Amount (USD)": "",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "",
        "Method of Pay": "",
        "Date": "",
        "Received Amount (EUR)": "",
        "Received Amount (USD)": "",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "Total",
        "Method of Pay": "",
        "Date": "",
        "Received Amount (EUR)": "€701,262.63",
        "Received Amount (USD)": "$762,241.99",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "",
        "Method of Pay": "",
        "Date": "",
        "Received Amount (EUR)": "",
        "Received Amount (USD)": "",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "",
        "Method of Pay": "",
        "Date": "",
        "Received Amount (EUR)": "",
        "Received Amount (USD)": "",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "",
        "Method of Pay": "",
        "Date": "",
        "Received Amount (EUR)": "",
        "Received Amount (USD)": "",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "",
        "Method of Pay": "",
        "Date": "",
        "Received Amount (EUR)": "",
        "Received Amount (USD)": "",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "",
        "Method of Pay": "",
        "Date": "",
        "Received Amount (EUR)": "",
        "Received Amount (USD)": "",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    },
    {
        "Regulatory Period": "",
        "Client Name": "GMV chart below",
        "Method of Pay": "",
        "Date": "",
        "Received Amount (EUR)": "",
        "Received Amount (USD)": "",
        "Total Received": "",
        "Shield Fee": "",
        "Client Transfer": "",
        "Gas Fees": "",
        "Completed": "",
        "Txn Hash": "",
        "Wallet Address": "",
        "Risk Score": "",
        "Self-hosted?": "",
        "KYC/AML": "",
        "Partner": "",
        "Onramp/Offramp": "",
        "Currency Pair": "",
        "Blockchain": "",
        "Notes": "",
        "Total GMV": "",
        "Total Net Profits": "",
        "# Transactions": "",
        "": ""
    }
    ]`;
    json = JSON.parse(json);
    let items = [];
    await volumeTransactionModel.deleteMany({ excelLoad: true });
    for (let i = 0; i < json.length; i++) {
        const element = json[i];
        let tx = element["Txn Hash"];

        if (element["Date"] != "" && element['Received Amount (USD)'] != "") {

            if (tx != "") {
                tx = tx.split("/");
                tx = tx[tx.length - 1];
            } else {
                tx = null;
            }
            let exist = await volumeTransactionModel.findOne({ tx: tx });
            // console.log(exist)
            if (exist == null || tx == null)
                items.push({
                    client: element['Client Name'],
                    business: element['Regulatory Period'],
                    methodPay: element['Method of Pay'],
                    date: new Date(element["Date"]),
                    receivedAmount: parseCurrencyString(element['Received Amount (USD)']),
                    symbol: "USDT",
                    tx: tx,
                    walletSend: element["Wallet Address"],
                    excelLoad: true
                });
        }
    }
    console.log(items.length);
    await volumeTransactionModel.insertMany(items)
    logger.success("insert data excel to volumeTransactions finish")

}

// loadTransactionsExcel();




router.get('/totalReceivedAmountByDay', async (req, res) => {
    try {
        const results = await VolumeTransactionController.getTotalReceivedAmountByDay();
        res.json(response(results, 'success'));
    } catch (error) {
        handleHttpError(error, res);
    }
});

router.get('/totalReceivedAmountByMonth', async (req, res) => {
    try {
        const results = await VolumeTransactionController.getTotalReceivedAmountByMonth();
        res.json(response(results, 'success'));
    } catch (error) {
        handleHttpError(error, res);
    }
});
router.post('/', authAdmin, async (req, res) => {
    try {
        const transaction = await VolumeTransactionController.createTransaction(req.body);
        res.json(response(transaction, 'success'));
    } catch (error) {
        handleHttpError(error, res);
    }
});

router.get('/', async (req, res) => {
    try {
        const transactions = await VolumeTransactionController.getTransactions();
        res.json(response(transactions, 'success'));
    } catch (error) {
        handleHttpError(error, res);
    }
});

router.get('/:id', async (req, res) => {
    try {
        const transaction = await VolumeTransactionController.getTransactionById(req.params.id);
        if (!transaction) {
            return res.status(404).json(response('Transaction not found', 'error'));
        }
        res.json(response(transaction, 'success'));
    } catch (error) {
        handleHttpError(error, res);
    }
});

router.put('/:id', authAdmin, async (req, res) => {
    try {
        const transaction = await VolumeTransactionController.updateTransaction({ _id: req.params.id }, req.body);
        if (!transaction) {
            return res.status(404).json(response('Transaction not found', 'error'));
        }
        res.json(response(transaction, 'success'));
    } catch (error) {
        handleHttpError(error, res);
    }
});

router.delete('/:id', authAdmin, async (req, res) => {
    try {
        const transaction = await VolumeTransactionController.deleteTransaction({ _id: req.params.id });
        if (!transaction) {
            return res.status(404).json(response('Transaction not found', 'error'));
        }
        res.json(response('Transaction deleted', 'success'));
    } catch (error) {
        handleHttpError(error, res);
    }
});

module.exports = router;
